name: basir_core_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  dio: ^4.0.6
  dio_logging_interceptor: ^1.0.1
  shared_preferences: ^2.0.17
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^7.0.1
  tcp_socket_connection: ^0.3.1
  grpc: ^3.0.2
  protoc_plugin: ^20.0.0
  protobuf: ^2.1.0
  # dio_logging_interceptor: ^1.0.1
#   path: ^1.8.0
  build_runner: ^2.3.3
  hive_generator: ^1.1.1
  web_socket_channel: ^2.3.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
